import { FoodLog } from "../types/models";

export const testFoodLogs: Omit<FoodLog, "id" | "logDate" | "createdAt">[] = [
  {
    title: "🍓 Greek Yogurt",
    description: "Plain Greek yogurt topped with berries and honey",
    foodComponents: [
      {
        amount: 200,
        name: "Greek yogurt",
        unit: "g",
        calories: 130,
        protein: 17,
        carbs: 8,
        fat: 5,
      },
      {
        amount: 60,
        name: "Mixed berries",
        unit: "g",
        calories: 30,
        protein: 1,
        carbs: 6,
        fat: 0,
      },
      {
        amount: 15,
        name: "Honey",
        unit: "ml",
        calories: 60,
        protein: 0,
        carbs: 14,
        fat: 0,
      },
    ],
    calories: 220,
    protein: 18,
    carbs: 28,
    fat: 5,
    isEstimating: false,
  },
  {
    title: "🥑 Avocado Toast",
    description: "Whole grain toast with mashed avocado and olive oil",
    foodComponents: [
      {
        amount: 2,
        name: "Whole grain bread slice",
        unit: "piece",
        recommendedMeasurement: { amount: 70, unit: "g" },
        calories: 140,
        protein: 6,
        carbs: 30,
        fat: 2,
      },
      {
        amount: 90,
        name: "Mashed avocado",
        unit: "g",
        calories: 130,
        protein: 2,
        carbs: 2,
        fat: 13,
      },
      {
        amount: 10,
        name: "Olive oil",
        unit: "ml",
        calories: 70,
        protein: 0,
        carbs: 0,
        fat: 7,
      },
    ],
    calories: 340,
    protein: 8,
    carbs: 32,
    fat: 22,
    isEstimating: false,
  },
  {
    title: "🥪 Turkey Sandwich",
    description: "Turkey breast with crisp veggies on whole wheat bread",
    foodComponents: [
      {
        amount: 2,
        name: "Whole wheat bread slice",
        unit: "piece",
        recommendedMeasurement: { amount: 80, unit: "g" },
        calories: 180,
        protein: 8,
        carbs: 36,
        fat: 4,
      },
      {
        amount: 120,
        name: "Turkey breast",
        unit: "g",
        calories: 180,
        protein: 22,
        carbs: 0,
        fat: 4,
      },
      {
        amount: 40,
        name: "Tomato slices",
        unit: "g",
        calories: 15,
        protein: 1,
        carbs: 2,
        fat: 0,
      },
      {
        amount: 30,
        name: "Lettuce",
        unit: "g",
        calories: 15,
        protein: 1,
        carbs: 2,
        fat: 0,
      },
      {
        amount: 15,
        name: "Mustard",
        unit: "ml",
        calories: 20,
        protein: 0,
        carbs: 2,
        fat: 4,
      },
    ],
    calories: 410,
    protein: 32,
    carbs: 42,
    fat: 12,
    isEstimating: false,
  },
  {
    title: "🥗 Quinoa Veggie Bowl",
    description: "Quinoa with roasted vegetables, chickpeas, and tahini",
    foodComponents: [
      {
        amount: 180,
        name: "Cooked quinoa",
        unit: "g",
        calories: 200,
        protein: 6,
        carbs: 35,
        fat: 3,
      },
      {
        amount: 120,
        name: "Roasted vegetables",
        unit: "g",
        calories: 80,
        protein: 3,
        carbs: 15,
        fat: 1,
      },
      {
        amount: 40,
        name: "Chickpeas",
        unit: "g",
        calories: 80,
        protein: 4,
        carbs: 10,
        fat: 2,
      },
      {
        amount: 20,
        name: "Lemon tahini dressing",
        unit: "ml",
        calories: 160,
        protein: 5,
        carbs: 4,
        fat: 14,
      },
    ],
    calories: 520,
    protein: 18,
    carbs: 64,
    fat: 20,
    isEstimating: false,
  },
  {
    title: "🍜 Chicken Stir Fry",
    description: "Grilled chicken with vegetables and brown rice",
    foodComponents: [
      {
        amount: 180,
        name: "Grilled chicken breast",
        unit: "g",
        calories: 220,
        protein: 38,
        carbs: 0,
        fat: 6,
      },
      {
        amount: 150,
        name: "Stir-fried vegetables",
        unit: "g",
        calories: 130,
        protein: 4,
        carbs: 15,
        fat: 10,
      },
      {
        amount: 150,
        name: "Cooked brown rice",
        unit: "g",
        calories: 250,
        protein: 6,
        carbs: 45,
        fat: 2,
      },
      {
        amount: 15,
        name: "Soy sauce",
        unit: "ml",
        calories: 20,
        protein: 0,
        carbs: 2,
        fat: 0,
      },
    ],
    calories: 620,
    protein: 48,
    carbs: 62,
    fat: 18,
    isEstimating: false,
  },
  {
    title: "🐟 Salmon Plate",
    description: "Baked salmon with rice and asparagus",
    foodComponents: [
      {
        amount: 150,
        name: "Baked salmon",
        unit: "g",
        calories: 280,
        protein: 30,
        carbs: 0,
        fat: 15,
      },
      {
        amount: 160,
        name: "Steamed jasmine rice",
        unit: "g",
        calories: 200,
        protein: 6,
        carbs: 40,
        fat: 2,
      },
      {
        amount: 80,
        name: "Roasted asparagus",
        unit: "g",
        calories: 20,
        protein: 2,
        carbs: 5,
        fat: 0,
      },
      {
        amount: 5,
        name: "Olive oil",
        unit: "ml",
        calories: 40,
        protein: 0,
        carbs: 0,
        fat: 5,
      },
    ],
    calories: 540,
    protein: 38,
    carbs: 45,
    fat: 22,
    isEstimating: false,
  },
  {
    title: "🥣 Overnight Oats",
    description: "Oats soaked in almond milk with chia seeds and berries",
    foodComponents: [
      {
        amount: 60,
        name: "Rolled oats",
        unit: "g",
        calories: 200,
        protein: 7,
        carbs: 35,
        fat: 4,
      },
      {
        amount: 200,
        name: "Almond milk",
        unit: "ml",
        calories: 40,
        protein: 1,
        carbs: 2,
        fat: 2,
      },
      {
        amount: 20,
        name: "Chia seeds",
        unit: "g",
        calories: 100,
        protein: 4,
        carbs: 8,
        fat: 6,
      },
      {
        amount: 50,
        name: "Blueberries",
        unit: "g",
        calories: 40,
        protein: 0,
        carbs: 7,
        fat: 0,
      },
    ],
    calories: 380,
    protein: 12,
    carbs: 52,
    fat: 12,
    isEstimating: false,
  },
  {
    title: "🥤 Protein Shake",
    description: "Chocolate protein blended with milk and banana",
    foodComponents: [
      {
        amount: 30,
        name: "Chocolate protein powder",
        unit: "g",
        calories: 110,
        protein: 23,
        carbs: 2,
        fat: 1,
      },
      {
        amount: 250,
        name: "Milk",
        unit: "ml",
        calories: 110,
        protein: 8,
        carbs: 10,
        fat: 7,
      },
      {
        amount: 1,
        name: "Banana",
        unit: "piece",
        recommendedMeasurement: { amount: 120, unit: "g" },
        calories: 100,
        protein: 1,
        carbs: 23,
        fat: 0,
      },
    ],
    calories: 320,
    protein: 32,
    carbs: 35,
    fat: 8,
    isEstimating: false,
  },
  {
    title: "🥕 Hummus Plate",
    description: "Hummus served with carrot and cucumber sticks",
    foodComponents: [
      {
        amount: 80,
        name: "Hummus",
        unit: "g",
        calories: 180,
        protein: 6,
        carbs: 12,
        fat: 12,
      },
      {
        amount: 120,
        name: "Carrot sticks",
        unit: "g",
        calories: 40,
        protein: 1,
        carbs: 8,
        fat: 0,
      },
      {
        amount: 100,
        name: "Cucumber sticks",
        unit: "g",
        calories: 40,
        protein: 4,
        carbs: 8,
        fat: 0,
      },
      {
        amount: 6,
        name: "Olive oil",
        unit: "ml",
        calories: 50,
        protein: 0,
        carbs: 0,
        fat: 6,
      },
    ],
    calories: 310,
    protein: 11,
    carbs: 28,
    fat: 18,
    isEstimating: false,
  },
  {
    title: "🍝 Beef Bolognese",
    description: "Spaghetti with beef bolognese and parmesan",
    foodComponents: [
      {
        amount: 200,
        name: "Cooked spaghetti",
        unit: "g",
        calories: 300,
        protein: 10,
        carbs: 60,
        fat: 2,
      },
      {
        amount: 140,
        name: "Beef bolognese sauce",
        unit: "g",
        calories: 300,
        protein: 15,
        carbs: 18,
        fat: 18,
      },
      {
        amount: 20,
        name: "Parmesan cheese",
        unit: "g",
        calories: 80,
        protein: 7,
        carbs: 0,
        fat: 6,
      },
    ],
    calories: 680,
    protein: 32,
    carbs: 78,
    fat: 26,
    isEstimating: false,
  },
  {
    title: "🍣 Salmon Nigiri",
    description: "Salmon nigiri pieces with soy sauce",
    foodComponents: [
      {
        amount: 8,
        name: "Salmon nigiri",
        unit: "piece",
        recommendedMeasurement: { amount: 360, unit: "g" },
        calories: 500,
        protein: 28,
        carbs: 76,
        fat: 12,
      },
      {
        amount: 10,
        name: "Soy sauce",
        unit: "ml",
        calories: 20,
        protein: 0,
        carbs: 2,
        fat: 0,
      },
    ],
    calories: 520,
    protein: 28,
    carbs: 78,
    fat: 12,
    isEstimating: false,
  },
  {
    title: "🍇 Fruit Plate",
    description: "Seasonal fruit selection",
    foodComponents: [
      {
        amount: 1,
        name: "Apple",
        unit: "piece",
        recommendedMeasurement: { amount: 180, unit: "g" },
        calories: 80,
        protein: 1,
        carbs: 20,
        fat: 0,
      },
      {
        amount: 1,
        name: "Orange",
        unit: "piece",
        recommendedMeasurement: { amount: 160, unit: "g" },
        calories: 80,
        protein: 1,
        carbs: 20,
        fat: 0,
      },
      {
        amount: 120,
        name: "Grapes",
        unit: "g",
        calories: 80,
        protein: 1,
        carbs: 22,
        fat: 1,
      },
    ],
    calories: 240,
    protein: 3,
    carbs: 62,
    fat: 1,
    isEstimating: false,
  },
];
